"""Models package."""

from app.models.database import (
    Base,
    PromptGeneration,
    PromptVariant,
    PromptVariantHistory,
    VariantStatus,
    HistoryAction,
    get_db,
    init_db,
    close_db,
    AsyncSessionLocal,
)
from app.models.schemas import (
    TemplateInfo,
    TemplateListResponse,
    GeneratePromptRequest,
    PromptGenerationResponse,
    GenerationListResponse,
    CreateVariantRequest,
    UpdateVariantRequest,
    ActivateVariantRequest,
    ChangeVariantStatusRequest,
    PromptVariantResponse,
    VariantListResponse,
    VariantHistoryResponse,
    HistoryListResponse,
    ComposePromptRequest,
    ComposePromptResponse,
    HealthResponse,
    DetailedHealthResponse,
    ErrorResponse,
    ValidationErrorResponse,
)

__all__ = [
    # Database models
    "Base",
    "PromptGeneration",
    "PromptVariant",
    "PromptVariantHistory",
    "VariantStatus",
    "HistoryAction",
    "get_db",
    "init_db",
    "close_db",
    "AsyncSessionLocal",
    # Schemas
    "TemplateInfo",
    "TemplateListResponse",
    "GeneratePromptRequest",
    "PromptGenerationResponse",
    "GenerationListResponse",
    "CreateVariantRequest",
    "UpdateVariantRequest",
    "ActivateVariantRequest",
    "ChangeVariantStatusRequest",
    "PromptVariantResponse",
    "VariantListResponse",
    "VariantHistoryResponse",
    "HistoryListResponse",
    "ComposePromptRequest",
    "ComposePromptResponse",
    "HealthResponse",
    "DetailedHealthResponse",
    "ErrorResponse",
    "ValidationErrorResponse",
]
